/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xss_mobile_activity_jnitest_NdkUtil */

#ifndef _Included_com_xss_mobile_activity_jnitest_NdkUtil
#define _Included_com_xss_mobile_activity_jnitest_NdkUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xss_mobile_activity_jnitest_NdkUtil
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xss_mobile_activity_jnitest_NdkUtil_getCLanguageString
  (JNIEnv *, jclass);

/*
 * Class:     com_xss_mobile_activity_jnitest_NdkUtil
 * Method:    callJavaMethodFromJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xss_mobile_activity_jnitest_NdkUtil_callJavaMethodFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
